# Generated by Django 5.2.3 on 2025-07-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('max_capacity', models.IntegerField()),
                ('description', models.TextField()),
                ('start_at', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('User_cpf', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
        migrations.CreateModel(
            name='EventAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=60)),
                ('neighborhood', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=5)),
                ('complement', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('max_capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('reserved', 'Reservado'), ('unavailable', 'Indisponível')], default='available', max_length=50)),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=36)),
                ('user_cpf', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('realizado', 'Realizado')], default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sector')),
            ],
        ),
    ]
