# Generated by Django 5.2.3 on 2025-06-27 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('max_capacity', models.IntegerField()),
                ('description', models.TextField()),
                ('start_at', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('role', models.CharField(default='Client')),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=60)),
                ('neighborhood', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=5)),
                ('complement', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('max_capacity', models.IntegerField()),
                ('status', models.CharField(default='available', max_length=50)),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('row', models.CharField(max_length=1)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('Sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=36)),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('Seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seat')),
                ('User_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='User_cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
