# Generated by Django 5.2.3 on 2025-07-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='User_cpf',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='User_cpf',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
