# Generated by Django 5.2.3 on 2025-07-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user_cpf',
            new_name='User_cpf',
        ),
    ]
