# Generated by Django 5.2.5 on 2025-08-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_cpf_ticket_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cpf_cliente',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF do Cliente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email do Cliente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do Cliente'),
        ),
    ]
