# Generated by Django 5.2.3 on 2025-07-20 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ticket_user_cpf_alter_event_user_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventadress',
            name='Event_id',
        ),
        migrations.AddField(
            model_name='eventadress',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
    ]
