# Generated by Django 5.2.3 on 2025-07-20 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_ticket_seat_id_delete_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('reserved', 'Reservado'), ('unavailable', 'Indisponível')], default='available', max_length=50),
        ),
    ]
