# Generated by Django 5.2.3 on 2025-07-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ticket_sector_alter_sector_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('realizado', 'Realizado')], default='pendente', max_length=20),
        ),
    ]
